export const GETGOODSLIST = 'GETGOODSLIST';
export const GETGOODSDETAILS = 'GETGOODSDETAILS';
export const SETSTORE_INFO = 'SETSTORE_INFO';
export const SETPRODUCTCATEGORY = 'SETPRODUCTCATEGORY';
export const GETCATEGORYS = 'GETCATEGORYS';
export const LOADLOGIN = 'LOADLOGIN';
