export const GETGOODSLIST = 'GETGOODSLIST';
export const GETGOODSDETAILS = 'GETGOODSDETAILS';
export const SETSTORE_INFO = 'SETSTORE_INFO';
export const UPDATEUSERINFO_INFO = 'UPDATEUSERINFO_INFO';
export const SETPRODUCTCATEGORY = 'SETPRODUCTCATEGORY';
export const GETCATEGORYS = 'GETCATEGORYS';
export const GET_STORE_INFO = 'GET_STORE_INFO';
export const LOADLOGIN = 'LOADLOGIN';
